# This Docker Compose file is to bring the local Pact Server up.
# In the production env, please use Pactflow.
version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    env_file:
      - docker.env

  broker_app:
    image: pactfoundation/pact-broker
    links:
      - postgres
    ports:
      - 8000:9292
    env_file:
      - docker.env
